spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:payment_transfer_application;;MODE=MySQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: sa
    hikari:
      connection-test-query: 'select 1'
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    database: h2
  flyway:
    locations: classpath:db/migration
server:
  error:
    include-message: always
accounts:
  mini-statement:
    size: 20